services:
  outline:
    image: docker.getoutline.com/outlinewiki/outline:latest
    container_name: outline_server
    env_file: ./docker.env
    ports:
      - "15240:3000"  # Porta mapeada para o serviço Outline
    depends_on:
      - postgres
      - redis
      - keycloak
    networks:
      - outline-network

  redis:
    image: redis
    container_name: outline_redis
    env_file: ./docker.env
    ports:
      - "6379:6379"
    volumes:
      - ./redis.conf:/redis.conf
    command: ["redis-server", "/redis.conf"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 30s
      retries: 3
    networks:
      - outline-network

  postgres:
    image: postgres
    container_name: outline_postgres
    env_file: ./docker.env
    ports:
      - "5432:5432"
    volumes:
      - database-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "outline", "-U", "user"]
      interval: 30s
      timeout: 20s
      retries: 3
    environment:
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'pass'
      POSTGRES_DB: 'outline'
    networks:
      - outline-network

  storage:
    image: quay.io/minio/minio
    container_name: outline_storage
    env_file: ./docker.env
    ports:
      - "9000:9000"
      - "9001:9001"
    entrypoint: sh
    command: -c 'minio server --console-address ":9001" /data/minio'
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - storage-data:/data
    environment:
      MINIO_ROOT_USER: 'minio'
      MINIO_ROOT_PASSWORD: 'minio123'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      outline-network:
        ipv4_address: 172.31.0.8

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak_server
    command: >
      start
      --proxy-headers=forwarded
      --import-realm
      --hostname=https://keycloak.mystartup.ucoip.pt
      --http-enabled=true
    ports:
      - "15443:8443"
      - "15280:8080"
    environment:
      PROXY_ADDRESS_FORWARDING: true
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'pass'
      POSTGRES_DB: 'keycloak'
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_LOG_LEVEL: DEBUG
    volumes:
      - keycloak_data:/opt/keycloak/data
      - ./outline-realm.json:/opt/keycloak/data/import/realm-config.json
    depends_on:
      - postgres
    networks:
      outline-network:
        ipv4_address: 172.31.0.7

volumes:
  storage-data:
  database-data:
  keycloak_data:

networks:
  outline-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.31.0.0/24
